# Generated by Django 5.0.2 on 2024-08-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_editora_cidade_editora_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
    ]
